module.exports = {
  algorithms: {
    arrays: require("./algorithms/arrays"),
    sorting: require("./algorithms/sorting"),
    searching: require("./algorithms/searching"),
    graphs: require("./algorithms/graphs"),
    strings: require("./algorithms/strings"),
    math: require("./algorithms/math"),
    dp: require("./algorithms/dp"),
    trees: require("./algorithms/trees"),
    heap: require("./algorithms/heap"),
    geometry: require("./algorithms/geometry"),
    random: require("./algorithms/random"),
    bit: require("./algorithms/bit"),
    greedy: require("./algorithms/greedy"),
    parsing: require("./algorithms/parsing"),
    backtracking: require("./algorithms/backtracking"),
    streaming: require("./algorithms/streaming"),
    numeric: require("./algorithms/numeric"),
  },
  dataStructures: {
    trees: require("./dataStructures/trees"),
    heap: require("./dataStructures/heap"),
    trie: require("./dataStructures/trie"),
    unionFind: require("./dataStructures/unionFind"),
    fenwickTree: require("./dataStructures/fenwickTree"),
    segmentTree: require("./dataStructures/segmentTree"),
    avlTree: require("./dataStructures/avlTree"),
    redBlackTree: require("./dataStructures/redBlackTree"),
    stack: require("./dataStructures/stack"),
    queue: require("./dataStructures/queue"),
    deque: require("./dataStructures/deque"),
    priorityQueue: require("./dataStructures/priorityQueue"),
    hashMap: require("./dataStructures/hashMap"),
    lruCache: require("./dataStructures/lruCache"),
    bloomFilter: require("./dataStructures/bloomFilter"),
    skipList: require("./dataStructures/skipList"),
    graph: require("./dataStructures/graph"),
    rope: require("./dataStructures/rope"),
    treap: require("./dataStructures/treap"),
    intervalTree: require("./dataStructures/intervalTree"),
    bTree: require("./dataStructures/bTree"),
    bPlusTree: require("./dataStructures/bPlusTree"),
    suffixTree: require("./dataStructures/suffixTree"),
  },
};
